### PR TITLE
Fix the noise issue

### PR DESCRIPTION
**Pull request by piyush-garg**
#19

### CODE REVIEW

**Comment by gabemontero** [comment]
Looks like a correct cherry-pick of https://github.com/openshift/jenkins-sync-plugin/commit/53ce3f4a12f1b246967a90bd6b08c4d429bb3d0b

**Comment by chmouel** [comment]
I guess the travis-ci never worked :\ were you able to test this @piyush1594  ?

**Comment by piyush-garg** [comment]
@gabemontero Yes it's cherry pick from there as mentioned by you in issue #19. Will this resolve the problem or anything else will be required?

@chmouel I am testing this right now. Give me few minutes, I will update.

**Comment by gabemontero** [comment]
@piyush1594 - https://github.com/fabric8io/jenkins-sync-plugin/issues/19 does sound just like issue we addressed with that commit

**Comment by piyush-garg** [comment]
Thanks @gabemontero Will provide more details after testing

**Review by rupalibehera — APPROVED** [review]

**Comment by piyush-garg** [comment]
Reverted as this did not fix the issue.

Any help @gabemontero

**Comment by gabemontero** [comment]
Not off the cuff @piyush1594 

I'd have to debug the situation vs. just read the bug description (which did sound like what the commit you reverted was dealing with)

Don't have cycles to drive such an investigation right now.  But in the short term could provide opinions on whatever debug analysis you come up with.

**Comment by piyush-garg** [comment]
Hey @gabemontero 

When the pipeline build is waiting for your user feedback to get approve or abort the pipeline its still updating the resource at an interval of 5 sec.

We want it to update the build only when there is a change in Jenkins.

```
19:54 $ oc get build -w app-test-3
NAME              TYPE              FROM         STATUS    STARTED         DURATION
app-test-3   JenkinsPipeline   Git@master   Running   6 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   7 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   8 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   9 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   10 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   10 minutes ago   
app-test-3   JenkinsPipeline   Git@master   Running   10 minutes ago  
```

**Comment by gabemontero** [comment]
Interesting ... I wonder if the user prompt / feedback element adds some nuance that we did not account for with the earlier commit.

I'll see if I can repro with our user prompt test case later today, and report back.

**Comment by gabemontero** [comment]
@piyush1594 - I suspect the prior commit you reverted, plus the change from https://github.com/openshift/jenkins-sync-plugin/pull/235, should address the frequent updates when the pipeline is paused for input

**Comment by piyush-garg** [comment]
Hey, @gabemontero I tried debugging it so This https://github.com/openshift/jenkins-sync-plugin/commit/53ce3f4a12f1b246967a90bd6b08c4d429bb3d0b#diff-b9ed119c66ed02d31e9cb3377f727207R202 always return `true` when it in the input stage. Then I tried removing two conditions 

1. https://github.com/openshift/jenkins-sync-plugin/commit/53ce3f4a12f1b246967a90bd6b08c4d429bb3d0b#diff-b9ed119c66ed02d31e9cb3377f727207R215 because our use case is like we do not even want to update at an interval of 30 secs. Correct if I am wrong @chmouel @hrishin @rupalibehera 

2. https://github.com/openshift/jenkins-sync-plugin/commit/53ce3f4a12f1b246967a90bd6b08c4d429bb3d0b#diff-b9ed119c66ed02d31e9cb3377f727207R230 Because I think it is returning `true` because of this condition and after that, it worked fine.

Correct me if i am wrong @gabemontero Thanks

EDIT :
Found out that your PR is regarding my second condition.Thanks for helping @gabemontero

**Comment by gabemontero** [comment]
OK, sounds like you are caught up @piyush1594 

On the 30 seconds thing, if you all wanted to make that configurable, even if it was via an env var / sys prop, I would be fine with merging any PR you submitted to https://github.com/openshift/jenkins-sync-plugin that mirrored what you did in the fork fabric has ... anything the progresses us getting back onto one fork again.

**Pull request merged**
